# Generated by Django 4.2.3 on 2023-07-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasanalay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='descripription',
            new_name='description',
        ),
    ]
