# Generated by Django 4.2.3 on 2023-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasanalay', '0002_rename_descripription_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
