# Generated by Django 4.2.3 on 2023-07-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasanalay', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
