# Generated by Django 4.2.3 on 2023-07-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasanalay', '0004_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
