name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install django
        python -m pip install Pillow
    - name: Run 
      run: |
        export DJANGO_SECRET_KEY='django-insecure-dnat$u6=9nfps1t_49$+w+!mwtroqte^#6_$eq*5=k5$jd(o-t'
        python manage.py runserver

